name: Build and Test
on:
  pull_request:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: NPM Install 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: npm install

      - name: Build HTML 🔧
        run: npm run build-html

      - name: Build HTML 🏗️
        run: npm run build-html

      - name: Build PDF 🏗️
        run: npm run build-pdf
